### ISSUE TITLE
 'termPutchar' was not declared in this scope

### ISSUE THREAD

**Issue by PandaBalls** [m5stack/m5-docs#128]
Arduino: 1.8.9 (Mac OS X), Board: "M5Stack-Core-ESP32, QIO, 40MHz, Default, 115200, None"

/Users/mac/Desktop/gps/gps.ino: In function 'void setup()':
gps:10:12: error: 'termInit' was not declared in this scope
   termInit();
            ^
/Users/mac/Desktop/gps/gps.ino: In function 'void loop()':
gps:22:19: error: 'termPutchar' was not declared in this scope
     termPutchar(ch);
                   ^
Multiple libraries were found for "SD.h"
 Used: /Users/mac/Library/Arduino15/packages/esp32/hardware/esp32/1.0.2/libraries/SD
 Not used: /Applications/Arduino.app/Contents/Java/libraries/SD
exit status 1
'termInit' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Gitshaoxiang** [comment]
same as the content in the log. you need check does have same name lib file in the lib path. the easy way is remove all the lib , just keep m5stack lib.

**Comment by sysdl132** [comment]
Can you give me the project you compile?(a link)

**Comment by sysdl132** [comment]
@PandaBalls tinybasic for m5?or others?

**Comment by LennartHennigs** [comment]
Well, it looks like this is not an answer to his question.
I had the same errors compiling `GPSRaw.ino` on a M5StickC.
There are two functions missing:

```
GPSRaw:17:12: error: 'termInit' was not declared in this scope
   termInit();

GPSRaw:30:19: error: 'termPutchar' was not declared in this scope
     termPutchar(ch);

```

After a lot of searching I found these two in [TFT_Terminal.ino](https://github.com/0x1abin/M5Stack_TinyBasicPlus/blob/master/TFT_Terminal.ino) so I could at leased figure out what they are for. But these are made for the M5Stack LCD and don't fully work as well.

Please update the example sketch with the proper functions.
