### ISSUE TITLE
Arduino IDE cannot upload to m5 stick c

### ISSUE THREAD

**Issue by jhoughjr** [m5stack/m5-docs#156]
Just got my m5 stick.
I've spent 2 days trying to upload an example after installing the board and library in Arduino.
The display flashes occasionally, but esptool comes back about missing packet header.
Everything at the latest version.

Holding reset does nothing, so I basically have a low quality paperweight.

**Comment by Gitshaoxiang** [comment]
hi.  did you  set Baudrate  to 115200  ?    select the board in M5StickC?
