### ISSUE TITLE
M5StickC Error 31 MPU6886 error

### ISSUE THREAD

**Issue by BrendanSimon** [m5stack/m5-docs#163]
I'm following the instructions to use VS Code with M5.

I've erased and burnt the firmware using the `EasyLoader_M5StickC_FactoryTest.exe`

I'm getting the following error on the M5StickC.

```
ERROR 31
--------------------
MPU6886 error
check Hardware
```

![m5StickC-Error-31-MPU6886-error](https://user-images.githubusercontent.com/472245/81490752-372d0300-92c9-11ea-834b-4ed5dc92b589.jpg)

Sounds like the firmware can't get a response from the MPU6886 device.

I can't see any files in VS Code either.  When I click on the COM8 (my com port for M5StickC) then vscode just spins forever but nothing appears.  I'm guessing that might be because of the ERROR above.

How can I resolve this ERROR 31.  Do I need to send the unit back or get a new one?  Or is there something I can do to try and get it working?

Is there different firmware I can try?

NOTE: I really need the MPU6886 as my application will process accelerations in all 3 axis.

Thanks, Brendan.

**Comment by EiichiroIto** [comment]
Hello.
I got same error message yesterday.
M5StickC has two variants, with MPU6886 and with SH200Q for IMU.
So if you have M5StickC with SH200Q. the error message occurs. (flip your device to see which one)
Because M5StickC IMU library detect two IMUs. You can use IMU in your program.
Thank you.

**Comment by kennethDow** [comment]
This resolution does not really help us in any way. The IMU example doesn't detect anything, neither do the other two examples. Factory example gets me error 31.

**Comment by BrendanSimon** [comment]
ok.  I flipped the device and it does say SH200Q on the sticker.

So, how do I get this working with VSCode so I can develop with MicroPython?  Is there different or updated firmware?

**Comment by EiichiroIto** [comment]
In C/C++, use M5.IMU object.
In MicroPython, following code can help you.
https://qiita.com/Lathe/items/3951f75688aa8fd6f56c
