### ISSUE TITLE
M5StickC with VS Code

### ISSUE THREAD

**Issue by BrendanSimon** [m5stack/m5-docs#164]
Does the M5StickC work with the VS Code extension `vscode-m5stack-mpy`?

https://marketplace.visualstudio.com/items?itemName=curdeveryday.vscode-m5stack-mpy

**Comment by Gudmundset** [comment]
Yes, just set the m5stickC to USB mode. It'll show up under the M5stack menu in Explorer as the COM port. You will probably need to use M5burner first, then when it's booting hit the M5 button and use the right-hand button to navigate to USB mode. I didn't need to use the API key like I do with the cloud UIFlow, so YMMV

**Comment by Gitshaoxiang** [comment]
some user feedback some version vscode m5stack plugin can't connect the device situation. so if you has same problem while you use, you could update the vscode to last version.

**Comment by BrendanSimon** [comment]
I have it working now :)  The problem is with my M5StickC (an older one) I need to short the G0 pin to GND.
I'm not sure if that is needed with newer devices.

**Comment by Gitshaoxiang** [comment]
maybe is the USB chip driver problem.  you could refer this tutorial to update the driver firmware

https://forum.m5stack.com/topic/1591/m5stickc-atom-on-macos-catalina-can-t-upload-esp32-timed-out-waiting-for-packet-header-solution/29

**Comment by Gitshaoxiang** [comment]
this issue is no update for a long time, it will be closed.
