### ISSUE TITLE
URGENT: Cellular UIFlow blockly documentation/examples

### ISSUE THREAD

**Issue by teiafra** [m5stack/m5-docs#169]
I need urgently description and instructions on how to use CELLULAR UIflow blocks in order to get COMx.LTE module to succesfully attach and establish a data connection. 
Also an example of blockly would be very appreciated (I got just an old SIM800 UIflow which looked pretty different) 

That palette of module.CELLULAR library is not described anywhere (only an Arduino code was found)!!
![Cellular palette](https://user-images.githubusercontent.com/63608242/94342973-3a752100-0015-11eb-9cc4-b347c1f11031.PNG)

**Comment by Gitshaoxiang** [comment]
you could refer this program.  

[Simple Calendar_v1.00.m5f.zip](https://github.com/m5stack/m5-docs/files/5437005/Simple.Calendar_v1.00.m5f.zip)
