### ISSUE TITLE
esp32cam Camera Interface PinMap is Error

### ISSUE THREAD

**Issue by slightc** [m5stack/m5-docs#170]
in doc pinmap is https://docs.m5stack.com/#/en/unit/esp32cam?id=pinmap
but in code pinmap is https://github.com/m5stack/M5Stack-Camera/blob/master/wifi/wifi_ap/main/config.h

in code pinmap is right

please fix doc!!

**Comment by Gitshaoxiang** [comment]
thank you feedback
