### ISSUE TITLE
CoreInk M5.shutdown()

### ISSUE THREAD

**Issue by ckuehnel** [m5stack/m5-docs#172]
I was going my first steps w/CoreInk. ESP32 Deep Sleep didi not work and M5.shutdown(seconds) give an error:

E:\Arduino\CoreInk_EnvII_Unit\CoreInk_EnvII_Unit.ino: In function 'void setup()':
CoreInk_EnvII_Unit:110:6: error: 'class M5CoreInk' has no member named 'shutdown'
   M5.shutdown(TIME_TO_SLEEP);

**Comment by Gitshaoxiang** [comment]
maybe the lib you used is not the last version.
