### ISSUE TITLE
documentation is looking horribly broken

### ISSUE THREAD

**Issue by gretel** [m5stack/m5-docs#174]
i.e. https://github.com/m5stack/m5-docs/blob/master/docs/en/core/atom_lite.md

- images lost inlcuding the important schematics
- markup borked
- including `script` tags

even `ttgo` can do better.

**Comment by koenvervloesem** [comment]
You're looking at the source code of the documentation. The result generated from this source is rendering fine: https://docs.m5stack.com/#/en/core/atom_lite

**Comment by gretel** [comment]
@koenvervloesem thanks - but the markdown is invalid, though.
